name: conan packaging for mc_rtc_data

on:
  repository_dispatch:
    types: [conan-master, conan-release]
  push:
    branches:
      - '**'
    tags:
      - v*
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
      if: startsWith(runner.os, 'Windows')
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: jrl-umi3218/github-actions/build-conan-package@master
      with:
        package: mc_rtc_data
        user: gergondet
        repository: multi-contact
        stable-channel: stable
        dev-channel: dev
        with-build-type: false
        force-upload: false
        with-docker: ${{ matrix.os == 'ubuntu-18.04' }}
        docker-images: '[debian:buster, ubuntu:20.04]'
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
