name: Package mc-rtc-data
on:
  repository_dispatch:
    types:
    - package-master
    - package-release
  push:
    paths-ignore:
    - doc/**
    - README.md
    - ".github/workflows/build.yml"
    branches:
    - "**"
    tags:
    - v*
  pull_request:
    branches:
    - "**"
jobs:
  package:
    uses: jrl-umi3218/github-actions/.github/workflows/package-project.yml@master
    with:
      with-ros: true
      matrix: |
        {
          "dist": ["bionic", "focal"],
          "arch": ["amd64"]
        }
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
